/* 
 * expert.ai Natural Language API
 *
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * The version of the OpenAPI document: v2
 * Contact: api.inquiry@expert.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ExpertIO.Client.Client.OpenAPIDateConverter;

namespace ExpertIO.Client.Model
{
    /// <summary>
    /// Main syncon info
    /// </summary>
    [DataContract]
    public partial class MainSyncon :  IEquatable<MainSyncon>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MainSyncon" /> class.
        /// </summary>
        /// <param name="syncon">ID used to look up Knowledge Graph data in the &#x60;knowledge&#x60; array.</param>
        /// <param name="lemma">Lemma.</param>
        /// <param name="score">Score assigned to the syncon to represent its relevance.</param>
        /// <param name="positions">Positions of the expressions of the syncon.</param>
        public MainSyncon(long syncon = default(long), string lemma = default(string), float score = default(float), List<DocumentPosition> positions = default(List<DocumentPosition>))
        {
            this.Syncon = syncon;
            this.Lemma = lemma;
            this.Score = score;
            this.Positions = positions;
        }
        
        /// <summary>
        /// ID used to look up Knowledge Graph data in the &#x60;knowledge&#x60; array
        /// </summary>
        /// <value>ID used to look up Knowledge Graph data in the &#x60;knowledge&#x60; array</value>
        [DataMember(Name="syncon", EmitDefaultValue=false)]
        public long Syncon { get; set; }

        /// <summary>
        /// Lemma
        /// </summary>
        /// <value>Lemma</value>
        [DataMember(Name="lemma", EmitDefaultValue=false)]
        public string Lemma { get; set; }

        /// <summary>
        /// Score assigned to the syncon to represent its relevance
        /// </summary>
        /// <value>Score assigned to the syncon to represent its relevance</value>
        [DataMember(Name="score", EmitDefaultValue=false)]
        public float Score { get; set; }

        /// <summary>
        /// Positions of the expressions of the syncon
        /// </summary>
        /// <value>Positions of the expressions of the syncon</value>
        [DataMember(Name="positions", EmitDefaultValue=false)]
        public List<DocumentPosition> Positions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MainSyncon {\n");
            sb.Append("  Syncon: ").Append(Syncon).Append("\n");
            sb.Append("  Lemma: ").Append(Lemma).Append("\n");
            sb.Append("  Score: ").Append(Score).Append("\n");
            sb.Append("  Positions: ").Append(Positions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MainSyncon);
        }

        /// <summary>
        /// Returns true if MainSyncon instances are equal
        /// </summary>
        /// <param name="input">Instance of MainSyncon to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MainSyncon input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Syncon == input.Syncon ||
                    (this.Syncon != null &&
                    this.Syncon.Equals(input.Syncon))
                ) && 
                (
                    this.Lemma == input.Lemma ||
                    (this.Lemma != null &&
                    this.Lemma.Equals(input.Lemma))
                ) && 
                (
                    this.Score == input.Score ||
                    (this.Score != null &&
                    this.Score.Equals(input.Score))
                ) && 
                (
                    this.Positions == input.Positions ||
                    this.Positions != null &&
                    input.Positions != null &&
                    this.Positions.SequenceEqual(input.Positions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Syncon != null)
                    hashCode = hashCode * 59 + this.Syncon.GetHashCode();
                if (this.Lemma != null)
                    hashCode = hashCode * 59 + this.Lemma.GetHashCode();
                if (this.Score != null)
                    hashCode = hashCode * 59 + this.Score.GetHashCode();
                if (this.Positions != null)
                    hashCode = hashCode * 59 + this.Positions.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
