/* 
 * expert.ai Natural Language API
 *
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * The version of the OpenAPI document: v2
 * Contact: api.inquiry@expert.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ExpertIO.Client.Client.OpenAPIDateConverter;

namespace ExpertIO.Client.Model
{
    /// <summary>
    /// Verb of a relation
    /// </summary>
    [DataContract]
    public partial class RelationVerb :  IEquatable<RelationVerb>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RelationVerb" /> class.
        /// </summary>
        /// <param name="text">Verb text.</param>
        /// <param name="lemma">Lemma.</param>
        /// <param name="syncon">ID used to look up Knowledge Graph data in the &#x60;knowledge&#x60; array.</param>
        /// <param name="type">Type.</param>
        /// <param name="phrase">Phrase index in the &#x60;phrases&#x60; array.</param>
        /// <param name="relevance">Relevance.</param>
        public RelationVerb(string text = default(string), string lemma = default(string), long syncon = default(long), string type = default(string), long phrase = default(long), long relevance = default(long))
        {
            this.Text = text;
            this.Lemma = lemma;
            this.Syncon = syncon;
            this.Type = type;
            this.Phrase = phrase;
            this.Relevance = relevance;
        }
        
        /// <summary>
        /// Verb text
        /// </summary>
        /// <value>Verb text</value>
        [DataMember(Name="text", EmitDefaultValue=false)]
        public string Text { get; set; }

        /// <summary>
        /// Lemma
        /// </summary>
        /// <value>Lemma</value>
        [DataMember(Name="lemma", EmitDefaultValue=false)]
        public string Lemma { get; set; }

        /// <summary>
        /// ID used to look up Knowledge Graph data in the &#x60;knowledge&#x60; array
        /// </summary>
        /// <value>ID used to look up Knowledge Graph data in the &#x60;knowledge&#x60; array</value>
        [DataMember(Name="syncon", EmitDefaultValue=false)]
        public long Syncon { get; set; }

        /// <summary>
        /// Type
        /// </summary>
        /// <value>Type</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Phrase index in the &#x60;phrases&#x60; array
        /// </summary>
        /// <value>Phrase index in the &#x60;phrases&#x60; array</value>
        [DataMember(Name="phrase", EmitDefaultValue=false)]
        public long Phrase { get; set; }

        /// <summary>
        /// Relevance
        /// </summary>
        /// <value>Relevance</value>
        [DataMember(Name="relevance", EmitDefaultValue=false)]
        public long Relevance { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RelationVerb {\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Lemma: ").Append(Lemma).Append("\n");
            sb.Append("  Syncon: ").Append(Syncon).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Phrase: ").Append(Phrase).Append("\n");
            sb.Append("  Relevance: ").Append(Relevance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RelationVerb);
        }

        /// <summary>
        /// Returns true if RelationVerb instances are equal
        /// </summary>
        /// <param name="input">Instance of RelationVerb to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RelationVerb input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                ) && 
                (
                    this.Lemma == input.Lemma ||
                    (this.Lemma != null &&
                    this.Lemma.Equals(input.Lemma))
                ) && 
                (
                    this.Syncon == input.Syncon ||
                    (this.Syncon != null &&
                    this.Syncon.Equals(input.Syncon))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Phrase == input.Phrase ||
                    (this.Phrase != null &&
                    this.Phrase.Equals(input.Phrase))
                ) && 
                (
                    this.Relevance == input.Relevance ||
                    (this.Relevance != null &&
                    this.Relevance.Equals(input.Relevance))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Text != null)
                    hashCode = hashCode * 59 + this.Text.GetHashCode();
                if (this.Lemma != null)
                    hashCode = hashCode * 59 + this.Lemma.GetHashCode();
                if (this.Syncon != null)
                    hashCode = hashCode * 59 + this.Syncon.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Phrase != null)
                    hashCode = hashCode * 59 + this.Phrase.GetHashCode();
                if (this.Relevance != null)
                    hashCode = hashCode * 59 + this.Relevance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
