/* 
 * expert.ai Natural Language API
 *
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * The version of the OpenAPI document: v2
 * Contact: api.inquiry@expert.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ExpertIO.Client.Client.OpenAPIDateConverter;

namespace ExpertIO.Client.Model
{
    /// <summary>
    /// Available taxonomies
    /// </summary>
    [DataContract]
    public partial class TaxonomiesResponse :  IEquatable<TaxonomiesResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TaxonomiesResponse" /> class.
        /// </summary>
        /// <param name="texonomies">List of taxonomies&#39; information.</param>
        public TaxonomiesResponse(List<TaxonomyInfo> texonomies = default(List<TaxonomyInfo>))
        {
            this.Texonomies = texonomies;
        }
        
        /// <summary>
        /// List of taxonomies&#39; information
        /// </summary>
        /// <value>List of taxonomies&#39; information</value>
        [DataMember(Name="texonomies", EmitDefaultValue=false)]
        public List<TaxonomyInfo> Texonomies { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TaxonomiesResponse {\n");
            sb.Append("  Texonomies: ").Append(Texonomies).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TaxonomiesResponse);
        }

        /// <summary>
        /// Returns true if TaxonomiesResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of TaxonomiesResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TaxonomiesResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Texonomies == input.Texonomies ||
                    this.Texonomies != null &&
                    input.Texonomies != null &&
                    this.Texonomies.SequenceEqual(input.Texonomies)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Texonomies != null)
                    hashCode = hashCode * 59 + this.Texonomies.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
