/* 
 * expert.ai Natural Language API
 *
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * The version of the OpenAPI document: v2
 * Contact: api.inquiry@expert.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ExpertIO.Client.Client.OpenAPIDateConverter;

namespace ExpertIO.Client.Model
{
    /// <summary>
    /// A taxonomy&#39;s categories tree
    /// </summary>
    [DataContract]
    public partial class Taxonomy :  IEquatable<Taxonomy>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Taxonomy" /> class.
        /// </summary>
        /// <param name="_namespace">Name of the software package containing the reference taxonomy.</param>
        /// <param name="taxonomy">Categories tree.</param>
        public Taxonomy(string _namespace = default(string), List<TaxonomyCategory> taxonomy = default(List<TaxonomyCategory>))
        {
            this.Namespace = _namespace;
            this._Taxonomy = taxonomy;
        }
        
        /// <summary>
        /// Name of the software package containing the reference taxonomy
        /// </summary>
        /// <value>Name of the software package containing the reference taxonomy</value>
        [DataMember(Name="namespace", EmitDefaultValue=false)]
        public string Namespace { get; set; }

        /// <summary>
        /// Categories tree
        /// </summary>
        /// <value>Categories tree</value>
        [DataMember(Name="taxonomy", EmitDefaultValue=false)]
        public List<TaxonomyCategory> _Taxonomy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Taxonomy {\n");
            sb.Append("  Namespace: ").Append(Namespace).Append("\n");
            sb.Append("  _Taxonomy: ").Append(_Taxonomy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Taxonomy);
        }

        /// <summary>
        /// Returns true if Taxonomy instances are equal
        /// </summary>
        /// <param name="input">Instance of Taxonomy to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Taxonomy input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Namespace == input.Namespace ||
                    (this.Namespace != null &&
                    this.Namespace.Equals(input.Namespace))
                ) && 
                (
                    this._Taxonomy == input._Taxonomy ||
                    this._Taxonomy != null &&
                    input._Taxonomy != null &&
                    this._Taxonomy.SequenceEqual(input._Taxonomy)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Namespace != null)
                    hashCode = hashCode * 59 + this.Namespace.GetHashCode();
                if (this._Taxonomy != null)
                    hashCode = hashCode * 59 + this._Taxonomy.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
