/* 
 * expert.ai Natural Language API
 *
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * The version of the OpenAPI document: v2
 * Contact: api.inquiry@expert.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using ExpertIO.Client.Client;
using ExpertIO.Client.Api;
using ExpertIO.Client.Model;

namespace ExpertIO.Client.Test
{
    /// <summary>
    ///  Class for testing DocumentAnalysisApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DocumentAnalysisApiTests
    {
        private DocumentAnalysisApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DocumentAnalysisApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentAnalysisApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' DocumentAnalysisApi
            //Assert.IsInstanceOf(typeof(DocumentAnalysisApi), instance);
        }

        
        /// <summary>
        /// Test AnalyzeContextLanguageAnalysisPost
        /// </summary>
        [Test]
        public void AnalyzeContextLanguageAnalysisPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string context = null;
            //string language = null;
            //string analysis = null;
            //AnalysisRequest analysisRequest = null;
            //var response = instance.AnalyzeContextLanguageAnalysisPost(context, language, analysis, analysisRequest);
            //Assert.IsInstanceOf(typeof(AnalyzeResponse), response, "response is AnalyzeResponse");
        }
        
        /// <summary>
        /// Test AnalyzeContextLanguagePost
        /// </summary>
        [Test]
        public void AnalyzeContextLanguagePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string context = null;
            //string language = null;
            //AnalysisRequest analysisRequest = null;
            //var response = instance.AnalyzeContextLanguagePost(context, language, analysisRequest);
            //Assert.IsInstanceOf(typeof(AnalyzeResponse), response, "response is AnalyzeResponse");
        }
        
    }

}
