/* 
 * expert.ai Natural Language API
 *
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * The version of the OpenAPI document: v2
 * Contact: api.inquiry@expert.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ExpertIO.Client.Api;
using ExpertIO.Client.Model;
using ExpertIO.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ExpertIO.Client.Test
{
    /// <summary>
    ///  Class for testing ContextInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContextInfoTests
    {
        // TODO uncomment below to declare an instance variable for ContextInfo
        //private ContextInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ContextInfo
            //instance = new ContextInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContextInfo
        /// </summary>
        [Test]
        public void ContextInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ContextInfo
            //Assert.IsInstanceOf(typeof(ContextInfo), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Languages'
        /// </summary>
        [Test]
        public void LanguagesTest()
        {
            // TODO unit test for the property 'Languages'
        }

    }

}
