/* 
 * expert.ai Natural Language API
 *
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * The version of the OpenAPI document: v2
 * Contact: api.inquiry@expert.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ExpertIO.Client.Api;
using ExpertIO.Client.Model;
using ExpertIO.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ExpertIO.Client.Test
{
    /// <summary>
    ///  Class for testing RelatedItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RelatedItemTests
    {
        // TODO uncomment below to declare an instance variable for RelatedItem
        //private RelatedItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RelatedItem
            //instance = new RelatedItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RelatedItem
        /// </summary>
        [Test]
        public void RelatedItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RelatedItem
            //Assert.IsInstanceOf(typeof(RelatedItem), instance);
        }


        /// <summary>
        /// Test the property 'Relation'
        /// </summary>
        [Test]
        public void RelationTest()
        {
            // TODO unit test for the property 'Relation'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Lemma'
        /// </summary>
        [Test]
        public void LemmaTest()
        {
            // TODO unit test for the property 'Lemma'
        }
        /// <summary>
        /// Test the property 'Syncon'
        /// </summary>
        [Test]
        public void SynconTest()
        {
            // TODO unit test for the property 'Syncon'
        }
        /// <summary>
        /// Test the property 'Vsyn'
        /// </summary>
        [Test]
        public void VsynTest()
        {
            // TODO unit test for the property 'Vsyn'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Phrase'
        /// </summary>
        [Test]
        public void PhraseTest()
        {
            // TODO unit test for the property 'Phrase'
        }
        /// <summary>
        /// Test the property 'Relevance'
        /// </summary>
        [Test]
        public void RelevanceTest()
        {
            // TODO unit test for the property 'Relevance'
        }
        /// <summary>
        /// Test the property 'Related'
        /// </summary>
        [Test]
        public void RelatedTest()
        {
            // TODO unit test for the property 'Related'
        }

    }

}
