/* 
 * expert.ai Natural Language API
 *
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * The version of the OpenAPI document: v2
 * Contact: api.inquiry@expert.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ExpertIO.Client.Api;
using ExpertIO.Client.Model;
using ExpertIO.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ExpertIO.Client.Test
{
    /// <summary>
    ///  Class for testing Token
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenTests
    {
        // TODO uncomment below to declare an instance variable for Token
        //private Token instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Token
            //instance = new Token();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Token
        /// </summary>
        [Test]
        public void TokenInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Token
            //Assert.IsInstanceOf(typeof(Token), instance);
        }


        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Test]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'End'
        /// </summary>
        [Test]
        public void EndTest()
        {
            // TODO unit test for the property 'End'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Pos'
        /// </summary>
        [Test]
        public void PosTest()
        {
            // TODO unit test for the property 'Pos'
        }
        /// <summary>
        /// Test the property 'Lemma'
        /// </summary>
        [Test]
        public void LemmaTest()
        {
            // TODO unit test for the property 'Lemma'
        }
        /// <summary>
        /// Test the property 'Syncon'
        /// </summary>
        [Test]
        public void SynconTest()
        {
            // TODO unit test for the property 'Syncon'
        }
        /// <summary>
        /// Test the property 'Morphology'
        /// </summary>
        [Test]
        public void MorphologyTest()
        {
            // TODO unit test for the property 'Morphology'
        }
        /// <summary>
        /// Test the property 'Dependency'
        /// </summary>
        [Test]
        public void DependencyTest()
        {
            // TODO unit test for the property 'Dependency'
        }
        /// <summary>
        /// Test the property 'Atoms'
        /// </summary>
        [Test]
        public void AtomsTest()
        {
            // TODO unit test for the property 'Atoms'
        }
        /// <summary>
        /// Test the property 'Paragraph'
        /// </summary>
        [Test]
        public void ParagraphTest()
        {
            // TODO unit test for the property 'Paragraph'
        }
        /// <summary>
        /// Test the property 'Sentence'
        /// </summary>
        [Test]
        public void SentenceTest()
        {
            // TODO unit test for the property 'Sentence'
        }
        /// <summary>
        /// Test the property 'Phrase'
        /// </summary>
        [Test]
        public void PhraseTest()
        {
            // TODO unit test for the property 'Phrase'
        }

    }

}
