/* 
 * expert.ai Natural Language API
 *
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * The version of the OpenAPI document: v2
 * Contact: api.inquiry@expert.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using ExpertIO.Client.Client;
using ExpertIO.Client.Model;

namespace ExpertIO.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDocumentClassificationApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Classification
        /// </summary>
        /// <remarks>
        /// Classification of the posted text
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxonomy">Taxonomy name; use the &#x60;taxonomies&#x60; resource to discover available taxonomies</param>
        /// <param name="language">Document language (code); use the &#x60;taxonomies&#x60; resource to discover the languages for which the taxonomy is available</param>
        /// <param name="analysisRequest">The document to be classified (optional)</param>
        /// <returns>CategorizeResponse</returns>
        CategorizeResponse CategorizeTaxonomyLanguagePost (string taxonomy, string language, AnalysisRequest analysisRequest = default(AnalysisRequest));

        /// <summary>
        /// Classification
        /// </summary>
        /// <remarks>
        /// Classification of the posted text
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxonomy">Taxonomy name; use the &#x60;taxonomies&#x60; resource to discover available taxonomies</param>
        /// <param name="language">Document language (code); use the &#x60;taxonomies&#x60; resource to discover the languages for which the taxonomy is available</param>
        /// <param name="analysisRequest">The document to be classified (optional)</param>
        /// <returns>ApiResponse of CategorizeResponse</returns>
        ApiResponse<CategorizeResponse> CategorizeTaxonomyLanguagePostWithHttpInfo (string taxonomy, string language, AnalysisRequest analysisRequest = default(AnalysisRequest));
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Classification
        /// </summary>
        /// <remarks>
        /// Classification of the posted text
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxonomy">Taxonomy name; use the &#x60;taxonomies&#x60; resource to discover available taxonomies</param>
        /// <param name="language">Document language (code); use the &#x60;taxonomies&#x60; resource to discover the languages for which the taxonomy is available</param>
        /// <param name="analysisRequest">The document to be classified (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of CategorizeResponse</returns>
        System.Threading.Tasks.Task<CategorizeResponse> CategorizeTaxonomyLanguagePostAsync (string taxonomy, string language, AnalysisRequest analysisRequest = default(AnalysisRequest), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Classification
        /// </summary>
        /// <remarks>
        /// Classification of the posted text
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxonomy">Taxonomy name; use the &#x60;taxonomies&#x60; resource to discover available taxonomies</param>
        /// <param name="language">Document language (code); use the &#x60;taxonomies&#x60; resource to discover the languages for which the taxonomy is available</param>
        /// <param name="analysisRequest">The document to be classified (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (CategorizeResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CategorizeResponse>> CategorizeTaxonomyLanguagePostWithHttpInfoAsync (string taxonomy, string language, AnalysisRequest analysisRequest = default(AnalysisRequest), CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DocumentClassificationApi : IDocumentClassificationApi
    {
        private ExpertIO.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentClassificationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DocumentClassificationApi(String basePath)
        {
            this.Configuration = new ExpertIO.Client.Client.Configuration { BasePath = basePath };

            ExceptionFactory = ExpertIO.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentClassificationApi"/> class
        /// </summary>
        /// <returns></returns>
        public DocumentClassificationApi()
        {
            this.Configuration = ExpertIO.Client.Client.Configuration.Default;

            ExceptionFactory = ExpertIO.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentClassificationApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DocumentClassificationApi(ExpertIO.Client.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = ExpertIO.Client.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = ExpertIO.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ExpertIO.Client.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExpertIO.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Classification Classification of the posted text
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxonomy">Taxonomy name; use the &#x60;taxonomies&#x60; resource to discover available taxonomies</param>
        /// <param name="language">Document language (code); use the &#x60;taxonomies&#x60; resource to discover the languages for which the taxonomy is available</param>
        /// <param name="analysisRequest">The document to be classified (optional)</param>
        /// <returns>CategorizeResponse</returns>
        public CategorizeResponse CategorizeTaxonomyLanguagePost (string taxonomy, string language, AnalysisRequest analysisRequest = default(AnalysisRequest))
        {
             ApiResponse<CategorizeResponse> localVarResponse = CategorizeTaxonomyLanguagePostWithHttpInfo(taxonomy, language, analysisRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Classification Classification of the posted text
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxonomy">Taxonomy name; use the &#x60;taxonomies&#x60; resource to discover available taxonomies</param>
        /// <param name="language">Document language (code); use the &#x60;taxonomies&#x60; resource to discover the languages for which the taxonomy is available</param>
        /// <param name="analysisRequest">The document to be classified (optional)</param>
        /// <returns>ApiResponse of CategorizeResponse</returns>
        public ApiResponse<CategorizeResponse> CategorizeTaxonomyLanguagePostWithHttpInfo (string taxonomy, string language, AnalysisRequest analysisRequest = default(AnalysisRequest))
        {
            // verify the required parameter 'taxonomy' is set
            if (taxonomy == null)
                throw new ApiException(400, "Missing required parameter 'taxonomy' when calling DocumentClassificationApi->CategorizeTaxonomyLanguagePost");
            // verify the required parameter 'language' is set
            if (language == null)
                throw new ApiException(400, "Missing required parameter 'language' when calling DocumentClassificationApi->CategorizeTaxonomyLanguagePost");

            var localVarPath = "/categorize/{taxonomy}/{language}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (taxonomy != null) localVarPathParams.Add("taxonomy", this.Configuration.ApiClient.ParameterToString(taxonomy)); // path parameter
            if (language != null) localVarPathParams.Add("language", this.Configuration.ApiClient.ParameterToString(language)); // path parameter
            if (analysisRequest != null && analysisRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(analysisRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = analysisRequest; // byte array
            }

            // authentication (bearerAuth) required
            // http beerer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CategorizeTaxonomyLanguagePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CategorizeResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CategorizeResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CategorizeResponse)));
        }

        /// <summary>
        /// Classification Classification of the posted text
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxonomy">Taxonomy name; use the &#x60;taxonomies&#x60; resource to discover available taxonomies</param>
        /// <param name="language">Document language (code); use the &#x60;taxonomies&#x60; resource to discover the languages for which the taxonomy is available</param>
        /// <param name="analysisRequest">The document to be classified (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of CategorizeResponse</returns>
        public async System.Threading.Tasks.Task<CategorizeResponse> CategorizeTaxonomyLanguagePostAsync (string taxonomy, string language, AnalysisRequest analysisRequest = default(AnalysisRequest), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<CategorizeResponse> localVarResponse = await CategorizeTaxonomyLanguagePostWithHttpInfoAsync(taxonomy, language, analysisRequest, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Classification Classification of the posted text
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxonomy">Taxonomy name; use the &#x60;taxonomies&#x60; resource to discover available taxonomies</param>
        /// <param name="language">Document language (code); use the &#x60;taxonomies&#x60; resource to discover the languages for which the taxonomy is available</param>
        /// <param name="analysisRequest">The document to be classified (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (CategorizeResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CategorizeResponse>> CategorizeTaxonomyLanguagePostWithHttpInfoAsync (string taxonomy, string language, AnalysisRequest analysisRequest = default(AnalysisRequest), CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'taxonomy' is set
            if (taxonomy == null)
                throw new ApiException(400, "Missing required parameter 'taxonomy' when calling DocumentClassificationApi->CategorizeTaxonomyLanguagePost");
            // verify the required parameter 'language' is set
            if (language == null)
                throw new ApiException(400, "Missing required parameter 'language' when calling DocumentClassificationApi->CategorizeTaxonomyLanguagePost");

            var localVarPath = "/categorize/{taxonomy}/{language}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (taxonomy != null) localVarPathParams.Add("taxonomy", this.Configuration.ApiClient.ParameterToString(taxonomy)); // path parameter
            if (language != null) localVarPathParams.Add("language", this.Configuration.ApiClient.ParameterToString(language)); // path parameter
            if (analysisRequest != null && analysisRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(analysisRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = analysisRequest; // byte array
            }

            // authentication (bearerAuth) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CategorizeTaxonomyLanguagePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CategorizeResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CategorizeResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CategorizeResponse)));
        }

    }
}
