/* 
 * expert.ai Natural Language API
 *
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * The version of the OpenAPI document: v2
 * Contact: api.inquiry@expert.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using ExpertIO.Client.Client;
using ExpertIO.Client.Model;

namespace ExpertIO.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDocumentAnalysisApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Specific analysis
        /// </summary>
        /// <remarks>
        /// Specific analysis of the posted text. Available analyses are: &lt;ul&gt;   &lt;li&gt;&lt;strong&gt;disambiguation&lt;/strong&gt;: linguistic analysis (text subdivision, part-of-speech tagging, morphological analysis, lemmatization, syntactic analysis and semantic analysis)&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;relevants&lt;/strong&gt;: keyphrase extraction&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;entities&lt;/strong&gt;: named entity recognition&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;relations&lt;/strong&gt;: relation extraction&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;sentiment&lt;/strong&gt;: sentiment analysis&lt;/li&gt; &lt;/ul&gt; 
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">Context name; use the &#x60;contexts&#x60; resource to discover available contexts</param>
        /// <param name="language">Document language (code)</param>
        /// <param name="analysis">Analysis name; use the &#x60;contexts&#x60; resource to determine if the context provides that analysis for the chosen language</param>
        /// <param name="analysisRequest">The document to be analyzed (optional)</param>
        /// <returns>AnalyzeResponse</returns>
        AnalyzeResponse AnalyzeContextLanguageAnalysisPost (string context, string language, string analysis, AnalysisRequest analysisRequest = default(AnalysisRequest));

        /// <summary>
        /// Specific analysis
        /// </summary>
        /// <remarks>
        /// Specific analysis of the posted text. Available analyses are: &lt;ul&gt;   &lt;li&gt;&lt;strong&gt;disambiguation&lt;/strong&gt;: linguistic analysis (text subdivision, part-of-speech tagging, morphological analysis, lemmatization, syntactic analysis and semantic analysis)&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;relevants&lt;/strong&gt;: keyphrase extraction&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;entities&lt;/strong&gt;: named entity recognition&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;relations&lt;/strong&gt;: relation extraction&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;sentiment&lt;/strong&gt;: sentiment analysis&lt;/li&gt; &lt;/ul&gt; 
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">Context name; use the &#x60;contexts&#x60; resource to discover available contexts</param>
        /// <param name="language">Document language (code)</param>
        /// <param name="analysis">Analysis name; use the &#x60;contexts&#x60; resource to determine if the context provides that analysis for the chosen language</param>
        /// <param name="analysisRequest">The document to be analyzed (optional)</param>
        /// <returns>ApiResponse of AnalyzeResponse</returns>
        ApiResponse<AnalyzeResponse> AnalyzeContextLanguageAnalysisPostWithHttpInfo (string context, string language, string analysis, AnalysisRequest analysisRequest = default(AnalysisRequest));
        /// <summary>
        /// Full analysis
        /// </summary>
        /// <remarks>
        /// Full analysis (i.e., sum of all available analyses) of the posted text
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">Context name; use the &#x60;contexts&#x60; resource to discover available contexts</param>
        /// <param name="language">Document language (code)</param>
        /// <param name="analysisRequest">The document to be analyzed (optional)</param>
        /// <returns>AnalyzeResponse</returns>
        AnalyzeResponse AnalyzeContextLanguagePost (string context, string language, AnalysisRequest analysisRequest = default(AnalysisRequest));

        /// <summary>
        /// Full analysis
        /// </summary>
        /// <remarks>
        /// Full analysis (i.e., sum of all available analyses) of the posted text
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">Context name; use the &#x60;contexts&#x60; resource to discover available contexts</param>
        /// <param name="language">Document language (code)</param>
        /// <param name="analysisRequest">The document to be analyzed (optional)</param>
        /// <returns>ApiResponse of AnalyzeResponse</returns>
        ApiResponse<AnalyzeResponse> AnalyzeContextLanguagePostWithHttpInfo (string context, string language, AnalysisRequest analysisRequest = default(AnalysisRequest));
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Specific analysis
        /// </summary>
        /// <remarks>
        /// Specific analysis of the posted text. Available analyses are: &lt;ul&gt;   &lt;li&gt;&lt;strong&gt;disambiguation&lt;/strong&gt;: linguistic analysis (text subdivision, part-of-speech tagging, morphological analysis, lemmatization, syntactic analysis and semantic analysis)&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;relevants&lt;/strong&gt;: keyphrase extraction&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;entities&lt;/strong&gt;: named entity recognition&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;relations&lt;/strong&gt;: relation extraction&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;sentiment&lt;/strong&gt;: sentiment analysis&lt;/li&gt; &lt;/ul&gt; 
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">Context name; use the &#x60;contexts&#x60; resource to discover available contexts</param>
        /// <param name="language">Document language (code)</param>
        /// <param name="analysis">Analysis name; use the &#x60;contexts&#x60; resource to determine if the context provides that analysis for the chosen language</param>
        /// <param name="analysisRequest">The document to be analyzed (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of AnalyzeResponse</returns>
        System.Threading.Tasks.Task<AnalyzeResponse> AnalyzeContextLanguageAnalysisPostAsync (string context, string language, string analysis, AnalysisRequest analysisRequest = default(AnalysisRequest), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Specific analysis
        /// </summary>
        /// <remarks>
        /// Specific analysis of the posted text. Available analyses are: &lt;ul&gt;   &lt;li&gt;&lt;strong&gt;disambiguation&lt;/strong&gt;: linguistic analysis (text subdivision, part-of-speech tagging, morphological analysis, lemmatization, syntactic analysis and semantic analysis)&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;relevants&lt;/strong&gt;: keyphrase extraction&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;entities&lt;/strong&gt;: named entity recognition&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;relations&lt;/strong&gt;: relation extraction&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;sentiment&lt;/strong&gt;: sentiment analysis&lt;/li&gt; &lt;/ul&gt; 
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">Context name; use the &#x60;contexts&#x60; resource to discover available contexts</param>
        /// <param name="language">Document language (code)</param>
        /// <param name="analysis">Analysis name; use the &#x60;contexts&#x60; resource to determine if the context provides that analysis for the chosen language</param>
        /// <param name="analysisRequest">The document to be analyzed (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (AnalyzeResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AnalyzeResponse>> AnalyzeContextLanguageAnalysisPostWithHttpInfoAsync (string context, string language, string analysis, AnalysisRequest analysisRequest = default(AnalysisRequest), CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Full analysis
        /// </summary>
        /// <remarks>
        /// Full analysis (i.e., sum of all available analyses) of the posted text
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">Context name; use the &#x60;contexts&#x60; resource to discover available contexts</param>
        /// <param name="language">Document language (code)</param>
        /// <param name="analysisRequest">The document to be analyzed (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of AnalyzeResponse</returns>
        System.Threading.Tasks.Task<AnalyzeResponse> AnalyzeContextLanguagePostAsync (string context, string language, AnalysisRequest analysisRequest = default(AnalysisRequest), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Full analysis
        /// </summary>
        /// <remarks>
        /// Full analysis (i.e., sum of all available analyses) of the posted text
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">Context name; use the &#x60;contexts&#x60; resource to discover available contexts</param>
        /// <param name="language">Document language (code)</param>
        /// <param name="analysisRequest">The document to be analyzed (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (AnalyzeResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AnalyzeResponse>> AnalyzeContextLanguagePostWithHttpInfoAsync (string context, string language, AnalysisRequest analysisRequest = default(AnalysisRequest), CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DocumentAnalysisApi : IDocumentAnalysisApi
    {
        private ExpertIO.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentAnalysisApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DocumentAnalysisApi(String basePath)
        {
            this.Configuration = new ExpertIO.Client.Client.Configuration { BasePath = basePath };

            ExceptionFactory = ExpertIO.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentAnalysisApi"/> class
        /// </summary>
        /// <returns></returns>
        public DocumentAnalysisApi()
        {
            this.Configuration = ExpertIO.Client.Client.Configuration.Default;

            ExceptionFactory = ExpertIO.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentAnalysisApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DocumentAnalysisApi(ExpertIO.Client.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = ExpertIO.Client.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = ExpertIO.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ExpertIO.Client.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExpertIO.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Specific analysis Specific analysis of the posted text. Available analyses are: &lt;ul&gt;   &lt;li&gt;&lt;strong&gt;disambiguation&lt;/strong&gt;: linguistic analysis (text subdivision, part-of-speech tagging, morphological analysis, lemmatization, syntactic analysis and semantic analysis)&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;relevants&lt;/strong&gt;: keyphrase extraction&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;entities&lt;/strong&gt;: named entity recognition&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;relations&lt;/strong&gt;: relation extraction&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;sentiment&lt;/strong&gt;: sentiment analysis&lt;/li&gt; &lt;/ul&gt; 
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">Context name; use the &#x60;contexts&#x60; resource to discover available contexts</param>
        /// <param name="language">Document language (code)</param>
        /// <param name="analysis">Analysis name; use the &#x60;contexts&#x60; resource to determine if the context provides that analysis for the chosen language</param>
        /// <param name="analysisRequest">The document to be analyzed (optional)</param>
        /// <returns>AnalyzeResponse</returns>
        public AnalyzeResponse AnalyzeContextLanguageAnalysisPost (string context, string language, string analysis, AnalysisRequest analysisRequest = default(AnalysisRequest))
        {
             ApiResponse<AnalyzeResponse> localVarResponse = AnalyzeContextLanguageAnalysisPostWithHttpInfo(context, language, analysis, analysisRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Specific analysis Specific analysis of the posted text. Available analyses are: &lt;ul&gt;   &lt;li&gt;&lt;strong&gt;disambiguation&lt;/strong&gt;: linguistic analysis (text subdivision, part-of-speech tagging, morphological analysis, lemmatization, syntactic analysis and semantic analysis)&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;relevants&lt;/strong&gt;: keyphrase extraction&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;entities&lt;/strong&gt;: named entity recognition&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;relations&lt;/strong&gt;: relation extraction&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;sentiment&lt;/strong&gt;: sentiment analysis&lt;/li&gt; &lt;/ul&gt; 
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">Context name; use the &#x60;contexts&#x60; resource to discover available contexts</param>
        /// <param name="language">Document language (code)</param>
        /// <param name="analysis">Analysis name; use the &#x60;contexts&#x60; resource to determine if the context provides that analysis for the chosen language</param>
        /// <param name="analysisRequest">The document to be analyzed (optional)</param>
        /// <returns>ApiResponse of AnalyzeResponse</returns>
        public ApiResponse<AnalyzeResponse> AnalyzeContextLanguageAnalysisPostWithHttpInfo (string context, string language, string analysis, AnalysisRequest analysisRequest = default(AnalysisRequest))
        {
            // verify the required parameter 'context' is set
            if (context == null)
                throw new ApiException(400, "Missing required parameter 'context' when calling DocumentAnalysisApi->AnalyzeContextLanguageAnalysisPost");
            // verify the required parameter 'language' is set
            if (language == null)
                throw new ApiException(400, "Missing required parameter 'language' when calling DocumentAnalysisApi->AnalyzeContextLanguageAnalysisPost");
            // verify the required parameter 'analysis' is set
            if (analysis == null)
                throw new ApiException(400, "Missing required parameter 'analysis' when calling DocumentAnalysisApi->AnalyzeContextLanguageAnalysisPost");

            var localVarPath = "/analyze/{context}/{language}/{analysis}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (context != null) localVarPathParams.Add("context", this.Configuration.ApiClient.ParameterToString(context)); // path parameter
            if (language != null) localVarPathParams.Add("language", this.Configuration.ApiClient.ParameterToString(language)); // path parameter
            if (analysis != null) localVarPathParams.Add("analysis", this.Configuration.ApiClient.ParameterToString(analysis)); // path parameter
            if (analysisRequest != null && analysisRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(analysisRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = analysisRequest; // byte array
            }

            // authentication (bearerAuth) required
            // http beerer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AnalyzeContextLanguageAnalysisPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AnalyzeResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AnalyzeResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AnalyzeResponse)));
        }

        /// <summary>
        /// Specific analysis Specific analysis of the posted text. Available analyses are: &lt;ul&gt;   &lt;li&gt;&lt;strong&gt;disambiguation&lt;/strong&gt;: linguistic analysis (text subdivision, part-of-speech tagging, morphological analysis, lemmatization, syntactic analysis and semantic analysis)&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;relevants&lt;/strong&gt;: keyphrase extraction&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;entities&lt;/strong&gt;: named entity recognition&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;relations&lt;/strong&gt;: relation extraction&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;sentiment&lt;/strong&gt;: sentiment analysis&lt;/li&gt; &lt;/ul&gt; 
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">Context name; use the &#x60;contexts&#x60; resource to discover available contexts</param>
        /// <param name="language">Document language (code)</param>
        /// <param name="analysis">Analysis name; use the &#x60;contexts&#x60; resource to determine if the context provides that analysis for the chosen language</param>
        /// <param name="analysisRequest">The document to be analyzed (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of AnalyzeResponse</returns>
        public async System.Threading.Tasks.Task<AnalyzeResponse> AnalyzeContextLanguageAnalysisPostAsync (string context, string language, string analysis, AnalysisRequest analysisRequest = default(AnalysisRequest), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<AnalyzeResponse> localVarResponse = await AnalyzeContextLanguageAnalysisPostWithHttpInfoAsync(context, language, analysis, analysisRequest, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Specific analysis Specific analysis of the posted text. Available analyses are: &lt;ul&gt;   &lt;li&gt;&lt;strong&gt;disambiguation&lt;/strong&gt;: linguistic analysis (text subdivision, part-of-speech tagging, morphological analysis, lemmatization, syntactic analysis and semantic analysis)&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;relevants&lt;/strong&gt;: keyphrase extraction&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;entities&lt;/strong&gt;: named entity recognition&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;relations&lt;/strong&gt;: relation extraction&lt;/li&gt;   &lt;li&gt;&lt;strong&gt;sentiment&lt;/strong&gt;: sentiment analysis&lt;/li&gt; &lt;/ul&gt; 
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">Context name; use the &#x60;contexts&#x60; resource to discover available contexts</param>
        /// <param name="language">Document language (code)</param>
        /// <param name="analysis">Analysis name; use the &#x60;contexts&#x60; resource to determine if the context provides that analysis for the chosen language</param>
        /// <param name="analysisRequest">The document to be analyzed (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (AnalyzeResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AnalyzeResponse>> AnalyzeContextLanguageAnalysisPostWithHttpInfoAsync (string context, string language, string analysis, AnalysisRequest analysisRequest = default(AnalysisRequest), CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'context' is set
            if (context == null)
                throw new ApiException(400, "Missing required parameter 'context' when calling DocumentAnalysisApi->AnalyzeContextLanguageAnalysisPost");
            // verify the required parameter 'language' is set
            if (language == null)
                throw new ApiException(400, "Missing required parameter 'language' when calling DocumentAnalysisApi->AnalyzeContextLanguageAnalysisPost");
            // verify the required parameter 'analysis' is set
            if (analysis == null)
                throw new ApiException(400, "Missing required parameter 'analysis' when calling DocumentAnalysisApi->AnalyzeContextLanguageAnalysisPost");

            var localVarPath = "/analyze/{context}/{language}/{analysis}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (context != null) localVarPathParams.Add("context", this.Configuration.ApiClient.ParameterToString(context)); // path parameter
            if (language != null) localVarPathParams.Add("language", this.Configuration.ApiClient.ParameterToString(language)); // path parameter
            if (analysis != null) localVarPathParams.Add("analysis", this.Configuration.ApiClient.ParameterToString(analysis)); // path parameter
            if (analysisRequest != null && analysisRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(analysisRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = analysisRequest; // byte array
            }

            // authentication (bearerAuth) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AnalyzeContextLanguageAnalysisPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AnalyzeResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AnalyzeResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AnalyzeResponse)));
        }

        /// <summary>
        /// Full analysis Full analysis (i.e., sum of all available analyses) of the posted text
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">Context name; use the &#x60;contexts&#x60; resource to discover available contexts</param>
        /// <param name="language">Document language (code)</param>
        /// <param name="analysisRequest">The document to be analyzed (optional)</param>
        /// <returns>AnalyzeResponse</returns>
        public AnalyzeResponse AnalyzeContextLanguagePost (string context, string language, AnalysisRequest analysisRequest = default(AnalysisRequest))
        {
             ApiResponse<AnalyzeResponse> localVarResponse = AnalyzeContextLanguagePostWithHttpInfo(context, language, analysisRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Full analysis Full analysis (i.e., sum of all available analyses) of the posted text
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">Context name; use the &#x60;contexts&#x60; resource to discover available contexts</param>
        /// <param name="language">Document language (code)</param>
        /// <param name="analysisRequest">The document to be analyzed (optional)</param>
        /// <returns>ApiResponse of AnalyzeResponse</returns>
        public ApiResponse<AnalyzeResponse> AnalyzeContextLanguagePostWithHttpInfo (string context, string language, AnalysisRequest analysisRequest = default(AnalysisRequest))
        {
            // verify the required parameter 'context' is set
            if (context == null)
                throw new ApiException(400, "Missing required parameter 'context' when calling DocumentAnalysisApi->AnalyzeContextLanguagePost");
            // verify the required parameter 'language' is set
            if (language == null)
                throw new ApiException(400, "Missing required parameter 'language' when calling DocumentAnalysisApi->AnalyzeContextLanguagePost");

            var localVarPath = "/analyze/{context}/{language}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (context != null) localVarPathParams.Add("context", this.Configuration.ApiClient.ParameterToString(context)); // path parameter
            if (language != null) localVarPathParams.Add("language", this.Configuration.ApiClient.ParameterToString(language)); // path parameter
            if (analysisRequest != null && analysisRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(analysisRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = analysisRequest; // byte array
            }

            // authentication (bearerAuth) required
            // http beerer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AnalyzeContextLanguagePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AnalyzeResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AnalyzeResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AnalyzeResponse)));
        }

        /// <summary>
        /// Full analysis Full analysis (i.e., sum of all available analyses) of the posted text
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">Context name; use the &#x60;contexts&#x60; resource to discover available contexts</param>
        /// <param name="language">Document language (code)</param>
        /// <param name="analysisRequest">The document to be analyzed (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of AnalyzeResponse</returns>
        public async System.Threading.Tasks.Task<AnalyzeResponse> AnalyzeContextLanguagePostAsync (string context, string language, AnalysisRequest analysisRequest = default(AnalysisRequest), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<AnalyzeResponse> localVarResponse = await AnalyzeContextLanguagePostWithHttpInfoAsync(context, language, analysisRequest, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Full analysis Full analysis (i.e., sum of all available analyses) of the posted text
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="context">Context name; use the &#x60;contexts&#x60; resource to discover available contexts</param>
        /// <param name="language">Document language (code)</param>
        /// <param name="analysisRequest">The document to be analyzed (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (AnalyzeResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AnalyzeResponse>> AnalyzeContextLanguagePostWithHttpInfoAsync (string context, string language, AnalysisRequest analysisRequest = default(AnalysisRequest), CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'context' is set
            if (context == null)
                throw new ApiException(400, "Missing required parameter 'context' when calling DocumentAnalysisApi->AnalyzeContextLanguagePost");
            // verify the required parameter 'language' is set
            if (language == null)
                throw new ApiException(400, "Missing required parameter 'language' when calling DocumentAnalysisApi->AnalyzeContextLanguagePost");

            var localVarPath = "/analyze/{context}/{language}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (context != null) localVarPathParams.Add("context", this.Configuration.ApiClient.ParameterToString(context)); // path parameter
            if (language != null) localVarPathParams.Add("language", this.Configuration.ApiClient.ParameterToString(language)); // path parameter
            if (analysisRequest != null && analysisRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(analysisRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = analysisRequest; // byte array
            }

            // authentication (bearerAuth) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AnalyzeContextLanguagePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AnalyzeResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (AnalyzeResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AnalyzeResponse)));
        }

    }
}
