/* 
 * expert.ai Natural Language API
 *
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * The version of the OpenAPI document: v2
 * Contact: api.inquiry@expert.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using ExpertIO.Client.Client;
using ExpertIO.Client.Model;

namespace ExpertIO.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITaxonomiesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Taxonomies information
        /// </summary>
        /// <remarks>
        /// Information about available taxonomies
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>TaxonomiesResponse</returns>
        TaxonomiesResponse TaxonomiesGet ();

        /// <summary>
        /// Taxonomies information
        /// </summary>
        /// <remarks>
        /// Information about available taxonomies
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of TaxonomiesResponse</returns>
        ApiResponse<TaxonomiesResponse> TaxonomiesGetWithHttpInfo ();
        /// <summary>
        /// Taxonomy tree
        /// </summary>
        /// <remarks>
        /// Detailed information about a taxonomy for a given language
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxonomy">Taxonomy name</param>
        /// <param name="language">Taxonomy language (code); use the &#x60;taxonomies&#x60; resource to discover the languages that the taxonomy supports</param>
        /// <returns>TaxonomyResponse</returns>
        TaxonomyResponse TaxonomiesTaxonomyLanguageGet (string taxonomy, string language);

        /// <summary>
        /// Taxonomy tree
        /// </summary>
        /// <remarks>
        /// Detailed information about a taxonomy for a given language
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxonomy">Taxonomy name</param>
        /// <param name="language">Taxonomy language (code); use the &#x60;taxonomies&#x60; resource to discover the languages that the taxonomy supports</param>
        /// <returns>ApiResponse of TaxonomyResponse</returns>
        ApiResponse<TaxonomyResponse> TaxonomiesTaxonomyLanguageGetWithHttpInfo (string taxonomy, string language);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Taxonomies information
        /// </summary>
        /// <remarks>
        /// Information about available taxonomies
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of TaxonomiesResponse</returns>
        System.Threading.Tasks.Task<TaxonomiesResponse> TaxonomiesGetAsync (CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Taxonomies information
        /// </summary>
        /// <remarks>
        /// Information about available taxonomies
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (TaxonomiesResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TaxonomiesResponse>> TaxonomiesGetWithHttpInfoAsync (CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Taxonomy tree
        /// </summary>
        /// <remarks>
        /// Detailed information about a taxonomy for a given language
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxonomy">Taxonomy name</param>
        /// <param name="language">Taxonomy language (code); use the &#x60;taxonomies&#x60; resource to discover the languages that the taxonomy supports</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of TaxonomyResponse</returns>
        System.Threading.Tasks.Task<TaxonomyResponse> TaxonomiesTaxonomyLanguageGetAsync (string taxonomy, string language, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Taxonomy tree
        /// </summary>
        /// <remarks>
        /// Detailed information about a taxonomy for a given language
        /// </remarks>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxonomy">Taxonomy name</param>
        /// <param name="language">Taxonomy language (code); use the &#x60;taxonomies&#x60; resource to discover the languages that the taxonomy supports</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (TaxonomyResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TaxonomyResponse>> TaxonomiesTaxonomyLanguageGetWithHttpInfoAsync (string taxonomy, string language, CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TaxonomiesApi : ITaxonomiesApi
    {
        private ExpertIO.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxonomiesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TaxonomiesApi(String basePath)
        {
            this.Configuration = new ExpertIO.Client.Client.Configuration { BasePath = basePath };

            ExceptionFactory = ExpertIO.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxonomiesApi"/> class
        /// </summary>
        /// <returns></returns>
        public TaxonomiesApi()
        {
            this.Configuration = ExpertIO.Client.Client.Configuration.Default;

            ExceptionFactory = ExpertIO.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxonomiesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TaxonomiesApi(ExpertIO.Client.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = ExpertIO.Client.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = ExpertIO.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ExpertIO.Client.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExpertIO.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Taxonomies information Information about available taxonomies
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>TaxonomiesResponse</returns>
        public TaxonomiesResponse TaxonomiesGet ()
        {
             ApiResponse<TaxonomiesResponse> localVarResponse = TaxonomiesGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Taxonomies information Information about available taxonomies
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of TaxonomiesResponse</returns>
        public ApiResponse<TaxonomiesResponse> TaxonomiesGetWithHttpInfo ()
        {

            var localVarPath = "/taxonomies";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (bearerAuth) required
            // http beerer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TaxonomiesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TaxonomiesResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (TaxonomiesResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TaxonomiesResponse)));
        }

        /// <summary>
        /// Taxonomies information Information about available taxonomies
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of TaxonomiesResponse</returns>
        public async System.Threading.Tasks.Task<TaxonomiesResponse> TaxonomiesGetAsync (CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<TaxonomiesResponse> localVarResponse = await TaxonomiesGetWithHttpInfoAsync(cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Taxonomies information Information about available taxonomies
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (TaxonomiesResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TaxonomiesResponse>> TaxonomiesGetWithHttpInfoAsync (CancellationToken cancellationToken = default(CancellationToken))
        {

            var localVarPath = "/taxonomies";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (bearerAuth) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TaxonomiesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TaxonomiesResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (TaxonomiesResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TaxonomiesResponse)));
        }

        /// <summary>
        /// Taxonomy tree Detailed information about a taxonomy for a given language
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxonomy">Taxonomy name</param>
        /// <param name="language">Taxonomy language (code); use the &#x60;taxonomies&#x60; resource to discover the languages that the taxonomy supports</param>
        /// <returns>TaxonomyResponse</returns>
        public TaxonomyResponse TaxonomiesTaxonomyLanguageGet (string taxonomy, string language)
        {
             ApiResponse<TaxonomyResponse> localVarResponse = TaxonomiesTaxonomyLanguageGetWithHttpInfo(taxonomy, language);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Taxonomy tree Detailed information about a taxonomy for a given language
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxonomy">Taxonomy name</param>
        /// <param name="language">Taxonomy language (code); use the &#x60;taxonomies&#x60; resource to discover the languages that the taxonomy supports</param>
        /// <returns>ApiResponse of TaxonomyResponse</returns>
        public ApiResponse<TaxonomyResponse> TaxonomiesTaxonomyLanguageGetWithHttpInfo (string taxonomy, string language)
        {
            // verify the required parameter 'taxonomy' is set
            if (taxonomy == null)
                throw new ApiException(400, "Missing required parameter 'taxonomy' when calling TaxonomiesApi->TaxonomiesTaxonomyLanguageGet");
            // verify the required parameter 'language' is set
            if (language == null)
                throw new ApiException(400, "Missing required parameter 'language' when calling TaxonomiesApi->TaxonomiesTaxonomyLanguageGet");

            var localVarPath = "/taxonomies/{taxonomy}/{language}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (taxonomy != null) localVarPathParams.Add("taxonomy", this.Configuration.ApiClient.ParameterToString(taxonomy)); // path parameter
            if (language != null) localVarPathParams.Add("language", this.Configuration.ApiClient.ParameterToString(language)); // path parameter

            // authentication (bearerAuth) required
            // http beerer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TaxonomiesTaxonomyLanguageGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TaxonomyResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (TaxonomyResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TaxonomyResponse)));
        }

        /// <summary>
        /// Taxonomy tree Detailed information about a taxonomy for a given language
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxonomy">Taxonomy name</param>
        /// <param name="language">Taxonomy language (code); use the &#x60;taxonomies&#x60; resource to discover the languages that the taxonomy supports</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of TaxonomyResponse</returns>
        public async System.Threading.Tasks.Task<TaxonomyResponse> TaxonomiesTaxonomyLanguageGetAsync (string taxonomy, string language, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<TaxonomyResponse> localVarResponse = await TaxonomiesTaxonomyLanguageGetWithHttpInfoAsync(taxonomy, language, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Taxonomy tree Detailed information about a taxonomy for a given language
        /// </summary>
        /// <exception cref="ExpertIO.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxonomy">Taxonomy name</param>
        /// <param name="language">Taxonomy language (code); use the &#x60;taxonomies&#x60; resource to discover the languages that the taxonomy supports</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (TaxonomyResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TaxonomyResponse>> TaxonomiesTaxonomyLanguageGetWithHttpInfoAsync (string taxonomy, string language, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'taxonomy' is set
            if (taxonomy == null)
                throw new ApiException(400, "Missing required parameter 'taxonomy' when calling TaxonomiesApi->TaxonomiesTaxonomyLanguageGet");
            // verify the required parameter 'language' is set
            if (language == null)
                throw new ApiException(400, "Missing required parameter 'language' when calling TaxonomiesApi->TaxonomiesTaxonomyLanguageGet");

            var localVarPath = "/taxonomies/{taxonomy}/{language}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (taxonomy != null) localVarPathParams.Add("taxonomy", this.Configuration.ApiClient.ParameterToString(taxonomy)); // path parameter
            if (language != null) localVarPathParams.Add("language", this.Configuration.ApiClient.ParameterToString(language)); // path parameter

            // authentication (bearerAuth) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TaxonomiesTaxonomyLanguageGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TaxonomyResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (TaxonomyResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TaxonomyResponse)));
        }

    }
}
